services:
  api-gateway:
    build:
      context: ./backend
      dockerfile: ./api-gateway/Dockerfile
    platform: linux/amd64
    ports:
      - 8080:8080
    environment:
      - PORT=8080
    depends_on:
      - accounts
      - products
      - reviews

  accounts:
    build:
      context: ./backend/graph-server/accounts
      dockerfile: Dockerfile
    ports:
      - 4001:4001
    environment:
      - PORT=4001

  products:
    build:
      context: ./backend/graph-server/products
      dockerfile: Dockerfile
    ports:
      - 4002:4002
    environment:
      - PORT=4002

  reviews:
    build:
      context: ./backend/graph-server/reviews
      dockerfile: Dockerfile
    ports:
      - 4003:4003
    environment:
      - PORT=4003
