services:
  api-gateway:
    build:
      context: ./backend/api-gateway
      dockerfile: Dockerfile
    ports:
      - 4000:4000

  accounts:
    build:
      context: ./backend/graph-server/accounts
      dockerfile: Dockerfile
    ports:
      - 4001:4001

  products:
    build:
      context: ./backend/graph-server/products
      dockerfile: Dockerfile
    ports:
      - 4002:4002

  reviews:
    build:
      context: ./backend/graph-server/reviews
      dockerfile: Dockerfile
    ports:
      - 4003:4003
