services:
  api-gateway:
    build:
      context: ./backend/api-gateway
      dockerfile: Dockerfile
    ports:
      - 4000:4000
    develop:
      watch:
        - action: sync+restart
          path: ./backend/api-gateway
          target: /app
          ignore:
            - build
            - node_modules
        - action: rebuild
          path: ./backend/api-gateway/package.json

  accounts:
    build:
      context: ./backend/graph-server/accounts
      dockerfile: Dockerfile
    ports:
      - 4001:4001
    develop:
      watch:
        - action: rebuild
          path: ./backend/graph-server/accounts

  products:
    build:
      context: ./backend/graph-server/products
      dockerfile: Dockerfile
    ports:
      - 4002:4002
    develop:
      watch:
        - action: rebuild
          path: ./backend/graph-server/products
