apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: graphql-sample-api-gateway
  annotations:
    run.googleapis.com/ingress: all
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/vpc-access-egress: all-traffic
        run.googleapis.com/network-interfaces: '[{"network":"graphql-sample-vpc","subnetwork":"graphql-sample-subnet"}]'
    spec:
      serviceAccountName: graphql-sample-api-gateway@velvety-glazing-420809.iam.gserviceaccount.com
      containers:
        - image: us-central1-docker.pkg.dev/velvety-glazing-420809/graphql-sample-repo/graphql-sample-api-gateway:latest
