apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: graphql-sample-products
  annotations:
    run.googleapis.com/ingress: internal
spec:
  template:
    spec:
      containers:
        - image: us-central1-docker.pkg.dev/velvety-glazing-420809/graphql-sample-repo/graphql-sample-products:latest
